#!/bin/bash
export DISPLAY=:0

uid=$(id -u)
export XDG_RUNTIME_DIR=/run/user/$uid

battery_level=`cat /sys/class/power_supply/BAT0/capacity`
battery_status=`cat /sys/class/power_supply/BAT0/status`
if [ $battery_status = "Charging" ] && [ $battery_level -ge 77 ];
then
	notify-send -u critical "Battery fully charged" ; spd-say "Battery fully charged"
fi
